comics:
    - PoorlyDrawnLines
    - SMBC
    - InvisibleBread
    - AmazingSuperPowers
    - FormalSweatPants
    - Garfield
    - MyExtraLife
    - XKCD
    - Channelate
    - Explosm
    - TheAkwardYeti
    - JoanCornella
    - CommitStrip
